-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1);
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1);
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', 0);

INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (2, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (3, 'ROLE_USER');

-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('TRIANGLE', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- SET @CATID=LAST_INSERT_ID();
-- INSERT INTO SHAPE_ATTRIBUTES (ATTRIBUTE_NAME, CATEGORY_ID) VALUES ('a', @CATID);
-- INSERT INTO SHAPE_ATTRIBUTES (ATTRIBUTE_NAME, CATEGORY_ID) VALUES ('a', @CATID);
-- INSERT INTO SHAPE_ATTRIBUTES (ATTRIBUTE_NAME, CATEGORY_ID) VALUES ('b', @CATID);
-- commit;
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('SQUARE', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('PARALLELOGRAM', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('RHOMBUS', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('KITE', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('TRAPEZIUM', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('CIRCLE', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");
-- INSERT INTO SHAPE_CATEGORY (USER_ID, AUTHORITY_NAME) VALUES ('ELLIPSE', "(sqrt( (a+b+c) * (a+b-c) * (b+c-a) * (c+a-b)))/4");


